name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ubah jika pakai branch lain

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./  # Folder proyek, bisa diganti jika perlu

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
